baralho = [
        {
        'nome': 'o envelope',
        'numero': '27',
        'naipe' : 'espadas',
        'valor' : '7',
        },
        {
            'nome' : 'O jardim',
            'número': '20',
            'naipe': 'espadas',
            'valor' : '8',
        },
        {
            'nome' : 'A ancôra',
            'número': '35',
            'naipe': 'espadas',
            'valor' : '9',
        },
        {
            'nome' : 'chicote',
            'número': '11',
            'naipe': 'paus',
            'valor': 'valete',
        },
        {
            'nome' : 'Os lírios',
            'número': '30',
            'naipe': 'espadas',
            'valor': 'Rei',
        },
        {
            'nome' : 'Os peixes',
            'número': '34',
            'naipe': 'ouros',
            'valor': 'Rei',
        },
        {
            'nome' : 'A cegonha',
            'número': '17',
            'naipe': 'copas',
            'valor': 'Rainha',
        },
        {
            'nome' : 'AS nuvens',
            'número': '6',
            'naipe': 'paus',
            'valor': 'Rei',
        },
        {
            'nome' : 'A torre',
            'número': '19',
            'naipe': 'espadas',
            'valor': '6',
        },
        {
            'nome' : 'A montanha',
            'número': '21',
            'naipe': 'paus',
            'valor': '8',
        },
        {
            'nome' : 'O buque',
            'número': '9',
            'naipe': 'espadas',
            'valor': 'Rainha',
        },
        {
            'nome' : 'O urso',
            'número': '15',
            'naipe': 'paus',
            'valor': '10',
        },
        {
            'nome' : 'O cavaleiro',
            'número': '1',
            'naipe': 'copas',
            'valor': '9',
        },
        {
            'nome' : 'A mulher',
            'número': '29',
            'naipe': 'espadas',
            'valor': '1',
        },
        {
            'nome' : 'A cruz',
            'número': '36',
            'naipe': 'paus',
            'valor': '6',
        },
        {
            'nome' : 'O livro',
            'número': '26',
            'naipe': 'ouros',
            'valor': '10',
        },
        {
            'nome' : 'O anel',
            'número': '25',
            'naipe': 'paus',
            'valor': '1',
        },
        {
            'nome' : 'A lua',
            'número': '32',
            'naipe': 'copas',
            'valor': '8',
        },
        {
            'nome' : 'Os ratos',
            'número': '23',
            'naipe': 'paus',
            'valor': '7',
        },
        {
            'nome' : 'A cobra',
            'número': '7',
            'naipe': 'paus',
            'valor': 'Rainha',
        },
        {
            'nome' : 'O cachorro',
            'número': '18',
            'naipe': 'copas',
            'valor': '10',
        },
        {
            'nome' : 'A raposa',
            'número': '14',
            'naipe': 'paus',
            'valor': '9',
        },
        {
            'nome' : 'A árvore',
            'número': '5',
            'naipe': 'copas',
            'valor': '7',
        },
        {
            'nome' : 'A casa',
            'número': '4',
            'naipe': 'copas',
            'valor': 'Rei',
        },
        {
            'nome' : 'O caixão',
            'número': '8',
            'naipe': 'ouros',
            'valor': '9',
        },
        {
            'nome' : 'As estrelas',
            'número': '16',
            'naipe': 'copas',
            'valor': '6',
        },
        {
            'nome' : 'O homem',
            'número': '28',
            'naipe': 'copas',
            'valor': '1',
        },
        {
            'nome' : 'O sol',
            'número': '31',
            'naipe': 'ouros',
            'valor': '1',
        },
        {
            'nome' : 'A criança',
            'número': '13',
            'naipe': 'espadas',
            'valor': 'valete',
        },
        {
            'nome' : 'Os caminhos',
            'número': '22',
            'naipe': 'ouros',
            'valor': 'Rainha',
        },
        {
            'nome' : 'O coração',
            'número': '24',
            'naipe': 'copas',
            'valor': 'valete',
        },
        {
            'nome' : 'A chave',
            'número': '33',
            'naipe': 'ouros',
            'valor': '8',
        },
        {
            'nome' : 'O trevo',
            'número': '2',
            'naipe': 'ouros',
            'valor': '6',
        },
        {
            'nome' : 'Os pássaros',
            'número': '12',
            'naipe': 'ouros',
            'valor': '7',
        },
        {
            'nome' : 'O navio',
            'número': '3',
            'naipe': 'espadas',
            'valor': '10',
        },
        {
            'nome' : 'A foice',
            'número': '10',
            'naipe': 'ouros',
            'valor': 'valete',
        },
    ]